### PR TITLE
Gulpfile

### PR DESCRIPTION
**Pull request by mseltzer94**
Initial start on gulpfile
- live reloading and enables a production environment 
- more work needs to be done (this currently exposes all of all source code, we probably don't want folders like test to be public), when we add in more tasks to gulp (such as minifying and copying over all javascript files the issue will be solved)

@brocef @dcalla02 @jclaw

### CODE REVIEW

**Comment by mseltzer94** [comment]
Don't worry about travis-ci until we have some tests - right now we have none so it fails.

**Comment by dcalla02** [comment]
what is?

Dan Callahan

**Comment by mseltzer94** [comment]
this is the initial serve startup script that enable us to startup the server on the development side (locally) and prodution (heroku). Currently heroku is using this branch but will be changed when merged: https://tuskdumbo.herokuapp.com/app

**Comment by dcalla02** [comment]
we can’t view the listings page on this link

Dan Callahan

**Comment by mseltzer94** [comment]
I'm just loading up whatever is in index.html - the same way its on master right now. Maybe those links need to be fixed not sure but thats a different subject than the gulpfile

**Comment by jclaw** [comment]
if it works i'm happy

**Pull request merged**
