### PR TITLE
Welcome screen

### PR DESCRIPTION
**Pull request by jclaw**
@dcalla02 @mseltzer94 Linked email field and checkbox to Mailchimp account. A confirmation email is sent to the user, and if they click confirm they are added to our mailing list. The "beta testing" data is retained and they are put into a separate group, so if we ever want to email people who are interested we can do that very easily.

### CODE REVIEW

**Comment by mseltzer94** [comment]
Holy shit approve well done

**Comment by mseltzer94** [comment]
Did you add this to the welcome folder?

**Comment by dcalla02** [comment]
nice work! approve
Dan Callahan

**Comment by jclaw** [comment]
No I didn’t add it to the welcome folder…how do I do that? just copy and paste into the file there?

Jackson

**Comment by mseltzer94** [comment]
Yup

**Comment by dcalla02** [comment]
Does this check if it is tufts.edu emails yet or no? It might be better that it's not

**Pull request merged**
